# Generated by Django 3.2.17 on 2023-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
