# Generated by Django 3.2.17 on 2023-02-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contributor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='status',
        ),
    ]
